<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ECS2CSVUserConfig [
<!ELEMENT ECS2CSVUserConfig (ColumnOptions ,IDOptions ,RowOptions ,HeaderOptions ,TrailerOptions ) >
  <!ATTLIST ECS2CSVUserConfig
  	DocumentType CDATA #REQUIRED
  	Version CDATA #REQUIRED
  >
  <!ELEMENT ColumnOptions (Column*)>
  <!ELEMENT Column (MissingValue*)>
  <!ATTLIST Column
  	Name CDATA #REQUIRED
  	DisplayName CDATA #IMPLIED
  >
  <!ELEMENT MissingValue (#PCDATA)>
  <!ATTLIST MissingValue
  	ApplyToNode CDATA #REQUIRED
  	Value CDATA #REQUIRED
  >
  <!ELEMENT IDOptions (IDOption*)>
  <!ELEMENT IDOption (DefaultFormat)>
  <!ATTLIST IDOption
  	NodeType CDATA #REQUIRED
  >
  <!ELEMENT DefaultFormat (Arg*)>
  <!ATTLIST DefaultFormat
  	FormatString CDATA #REQUIRED
  >
  <!ELEMENT Arg (#PCDATA)>
  <!ATTLIST Arg
  	DataSource CDATA #REQUIRED
  >
  <!ELEMENT RowOptions (Rows, Option*)>
  <!ELEMENT Rows (Row*)>
  <!ELEMENT Row (#PCDATA)>
  <!ATTLIST Row
  	SupportEndRow (YES|NO) "YES"
  	EndRow (YES | NO) "NO"
  	NodeType CDATA #REQUIRED
  >
  <!ELEMENT Option (#PCDATA)>
  <!ATTLIST Option
  	Name CDATA #REQUIRED
  	Value CDATA #REQUIRED
  >
  <!ELEMENT HeaderOptions (FormattedText*)>
  <!ELEMENT FormattedText (Arg*)>
  <!ATTLIST FormattedText
  	FormatString CDATA #REQUIRED
  >
  <!ELEMENT TrailerOptions (FormattedText*)>
  ]>

<ECS2CSVUserConfig DocumentType="NCPDP" Version="1.0">
	<ColumnOptions>
		<Column Name="#" Selected="YES"/>
		<Column Name="Transaction Position" Selected="YES"/>
		<Column Name="Transaction ID" Selected="YES"/>
		<Column Name="Transaction Name" Selected="YES"/>
		<Column Name="Segment Position" Selected="YES"/>
		<Column Name="Segment ID" Selected="YES"/>
		<Column Name="Segment Name" Selected="YES"/>
		<Column Name="Field Position" Selected="YES"/>
		<Column Name="Field ID" Selected="YES"/>
		<Column Name="Field Name" Selected="YES"/>
		<Column Name="Qualified Group Position" Selected="YES"/>
		<Column Name="Qualified Group ID" Selected="YES"/>
		<Column Name="Qualified Group Name" Selected="YES"/>
		<Column Name="Qualified Field Position" Selected="YES"/>
		<Column Name="Qualified Field ID" Selected="YES"/>
		<Column Name="Qualified Field Name" Selected="YES"/>
		<Column Name="Repeat Set Position" Selected="YES"/>
		<Column Name="Repeat Set ID" Selected="YES"/>
		<Column Name="Repeat Set Name" Selected="YES"/>
		<Column Name="Count Group Position" Selected="YES"/>
		<Column Name="Count Group ID" Selected="YES"/>
		<Column Name="Count Group Name" Selected="YES"/>
		<Column Name="Count Field Position" Selected="YES"/>
		<Column Name="Count Field ID" Selected="YES"/>
		<Column Name="Count Field Name" Selected="YES"/>
		<Column Name="Counter Group Position" Selected="YES"/>
		<Column Name="Counter Group ID" Selected="YES"/>
		<Column Name="Counter Group Name" Selected="YES"/>
		<Column Name="Iteration Field Position" Selected="YES"/>
		<Column Name="Iteration Field ID" Selected="YES"/>
		<Column Name="Iteration Field Name" Selected="YES"/>
		<Column Name="Requirement" Selected="YES"/>
		<Column Name="User Option" Selected="YES"/>
		<Column Name="Excluded" Selected="YES"/>
		<Column Name="Repeated" Selected="YES"/>
		<Column Name="Format" Selected="YES"/>
		<Column Name="Min Size" Selected="YES"/>
		<Column Name="Max Size" Selected="YES"/>
		<Column Name="Codelist" Selected="YES"/>
		<Column Name="Name" Selected="YES"/>
		<Column Name="Purpose" Selected="YES"/>
		<Column Name="Data Type" Selected="YES"/>
		<Column Name="Application Field Name" Selected="YES"/>
		<Column Name="Application Record" Selected="YES"/>
		<Column Name="Application Example" Selected="YES"/>
		<Column Name="UPath" Selected="NO"/>
		<Column Name="ID" Selected="NO"/>
		<Column Name="Application Mode" Selected="NO"/>
		<Column Name="Application Control" Selected="NO"/>
		<Column Name="Application Label" Selected="NO"/>
		<Column Name="Application Format" Selected="NO"/>
		<Column Name="Application Notes" Selected="NO"/>
		<Column Name="User Note 1" Selected="NO"/>
		<Column Name="User Note 2" Selected="NO"/>
		<Column Name="User Note 3" Selected="NO"/>
		<Column Name="User Note 4" Selected="NO"/>
		<Column Name="User Note 5" Selected="NO"/>
		<Column Name="User Note 6" Selected="NO"/>
		<Column Name="User Note 7" Selected="NO"/>
		<Column Name="User Note 8" Selected="NO"/>
		<Column Name="User Note 9" Selected="NO"/>
		<Column Name="User Note 10" Selected="NO"/>
		<Column Name="User Note 11" Selected="NO"/>
		<Column Name="User Note 12" Selected="NO"/>
		<Column Name="User Note 13" Selected="NO"/>
		<Column Name="User Note 14" Selected="NO"/>
		<Column Name="User Note 15" Selected="NO"/>
		<Column Name="User Note 16" Selected="NO"/>
		<Column Name="User Note 17" Selected="NO"/>
		<Column Name="User Note 18" Selected="NO"/>
		<Column Name="User Note 19" Selected="NO"/>
		<Column Name="User Note 20" Selected="NO"/>
	</ColumnOptions>
	<IDOptions>
		<IDOption NodeType="Transaction">
			<DefaultFormat FormatString="%s">
				<Arg DataSource="ID"/>
			</DefaultFormat>
		</IDOption>
		<IDOption NodeType="Segment">
			<DefaultFormat FormatString="%s">
				<Arg DataSource="ID"/>
			</DefaultFormat>
		</IDOption>
		<IDOption NodeType="RepeatSet">
			<DefaultFormat FormatString="%s">
				<Arg DataSource="ID"/>
			</DefaultFormat>
		</IDOption>
		<IDOption NodeType="QualifiedGroup">
			<DefaultFormat FormatString="%s">
				<Arg DataSource="ID"/>
			</DefaultFormat>
		</IDOption>
		<IDOption NodeType="CountGroup">
			<DefaultFormat FormatString="%s">
				<Arg DataSource="ID"/>
			</DefaultFormat>
		</IDOption>
		<IDOption NodeType="CounterGroup">
			<DefaultFormat FormatString="%s">
				<Arg DataSource="ID"/>
			</DefaultFormat>
		</IDOption>
		<IDOption NodeType="Field">
			<DefaultFormat FormatString="%s">
				<Arg DataSource="ID"/>
			</DefaultFormat>
		</IDOption>
		<IDOption NodeType="QualifiedField">
			<DefaultFormat FormatString="%s">
				<Arg DataSource="ID"/>
			</DefaultFormat>
		</IDOption>
		<IDOption NodeType="CountField">
			<DefaultFormat FormatString="%s">
				<Arg DataSource="ID"/>
			</DefaultFormat>
		</IDOption>
		<IDOption NodeType="IterationField">
			<DefaultFormat FormatString="%s">
				<Arg DataSource="ID"/>
			</DefaultFormat>
		</IDOption>
	</IDOptions>
	<RowOptions>
		<Rows>
			<Row NodeType="Transaction" EndRow="YES"/>
			<Row NodeType="Segment" EndRow="YES"/>
			<Row NodeType="RepeatSet" EndRow="YES"/>
			<Row NodeType="QualifiedGroup" EndRow="YES"/>
			<Row NodeType="CountGroup"/>
			<Row NodeType="CounterGroup"/>
			<Row NodeType="Field" SupportEndRow="NO"/>
			<Row NodeType="QualifiedField" SupportEndRow="NO"/>
			<Row NodeType="CountField" SupportEndRow="NO"/>
			<Row NodeType="IterationField" SupportEndRow="NO"/>
		</Rows>
		<Option Name="SuppressNotUsedNodes" Value="NO"/>
		<Option Name="SuppressExcludedNodes" Value="NO"/>
		<Option Name="SuppressExcludedCodes" Value="YES"/>
	</RowOptions>
	<HeaderOptions>
		<FormattedText FormatString=""/>
		<FormattedText FormatString=""/>
		<FormattedText FormatString=""/>
	</HeaderOptions>
	<TrailerOptions>
		<FormattedText FormatString=""/>
		<FormattedText FormatString=""/>
		<FormattedText FormatString=""/>
	</TrailerOptions>
</ECS2CSVUserConfig>